### ISSUE TITLE
Panic when adding 'tempfile' dependency

### ISSUE THREAD

**Issue by mbuesch** [geiger-rs/cargo-geiger#493]
cargo-geiger crashes, if I add the 'tempfile' dependency to a project:

```
$ RUST_BACKTRACE=1 cargo geiger -v
thread 'main' panicked at /.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.69.1/src/cargo/core/package.rs:708:9:               
assertion failed: self.pending_ids.insert(id)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
   3: cargo::core::package::Downloads::start
   4: cargo::core::package::PackageSet::get_many
   5: cargo::ops::cargo_clean::clean
   6: cargo_geiger::scan::rs_file::resolve_rs_file_deps
   7: cargo_geiger::scan::default::scan
   8: cargo_geiger::scan::default::table::scan_to_table
   9: cargo_geiger::scan::default::scan_unsafe
  10: cargo_geiger::scan::scan
  11: cargo_geiger::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

# How to reproduce?

```
cargo new geigertest
cd geigertest
cargo add tempfile
# tempfile v3.8.1
cargo geiger
# crash
```

# Versions

```
$ cargo geiger --version
cargo-geiger 0.11.6
$ rustc --version
rustc 1.74.1 (a28077b28 2023-12-04)
$ cargo --version
cargo 1.74.1 (ecb9851af 2023-10-18)
```

**Comment by pinkforest** [comment]
Please build & install v0.11.7 using `--locked` from git:

`cargo install --profile release --locked --git https://github.com/geiger-rs/cargo-geiger cargo-geiger`

Or use one of the pre-built binaries https://github.com/geiger-rs/cargo-geiger/releases/tag/cargo-geiger%40v0.11.7

If this issue persists please let me know what `rustup show` says

**Comment by mbuesch** [comment]
>I cannot replicate this problem by using --locked and / or 0.11.7

Ok, well I installed the latest version from crates.io.
I was not aware that the version from crates.io is outdated.

**Comment by pinkforest** [comment]
The crates.io is fine but you need to use `--locked` as there was some change that broke the runtime.

I just want to test in the newest version from git which has not been published yet.

**Comment by mbuesch** [comment]
>I just want to test in the newest version from git which has not been published yet

Yes, with git it doesn't crash.

**Comment by pinkforest** [comment]
Thanks for confirming - Closing as resolved - Will publish to crates.io the documentation fix to use `--locked` soon.
